### ISSUE TITLE
Unable to login using the API

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/csharp-lite#5]
Hello.
In a WPF project I've referenced the `Gedcomx.Api.Lite`.

I'm trying to execute the following:

    var sdk = new FamilySearchSDK(username: Username, password: Password, applicationKey: ClientId, applicationName: ApplicationName, version: "1.0.0");

Which throws an exception carrying the following message:

> Unable to obtain an access token. Check username, password and applicationKey

I've verified the parameters (except for version) to be as appearing in the FamilySearch developer [homepage](https://grms.force.com/Developer/FSDev_MyDevHomePage).
Here's a screenshot (the values in red indicate the constants used as parameters in my app):

![](http://i.imgur.com/CFmF0G0.png)

**Comment by misbach** [comment]
@weitzhandler It looks like you may need the username and password flow approved for your app key. Email me your app key and i'll activate it (misbach@familysearch.org)

**Comment by weitzhandler** [comment]
Issue solved, thank you @misbach!
